[player]

[transform]
[transform.scale]
x = 0.4
y = 1

[rigidbody]

[collider]

[sprite]
depth = 100
animations = [
    { name = "Idle", path = "./resources/animations/guardian/idle/{1-6}.png" },
    { name = "Walk", path = "./resources/animations/guardian/walk1/{1-14}.png" },
]
