[transform]
[transform.position]
x = -0.8
y = 0
[transform.scale]
x = 0.2
y = 1

[sprite]
depth = 1000
color = [0.1, 0.1, 0.1, 1]

[children]
objects = [{ path = "button/button.toml" }]
