[transform]
[transform.position]
x = 0
y = 0
[transform.scale]
x = 0.5
y = 0.1

[sprite]
depth = 1000
color = [0.9, 0.1, 0.1, 1]

[script]
path = "."
name = "button"

[custom]
test = "test"
